### ISSUE TITLE
dimond program

### ISSUE THREAD

**Issue by Mohamed-ElhajAbdou** [bio-ontology-research-group/deepgoplus#20]
im a windows user, so can you show me a full details steps of how to install it on winndows and how to run it 

   `diamond blastp -d data/train_data.dmnd -q data/test_data.fa --outfmt 6 qseqid sseqid bitscore > data/test_diamond.res`

thank in advance

**Comment by coolmaksat** [comment]
Hi, I think you can download diamond binaries for windows from here https://github.com/bbuchfink/diamond/releases/download/v0.9.31/diamond-windows.zip

**Comment by Mohamed-ElhajAbdou** [comment]
I think I have a problem with make and cmake programs I tried a lot to resolve the problem but I have nested problems that generated from making the diamond program is there any author way for installing the diamond this link the executable file has an error during the installation 
Could you kindly provide us with the diamond.res file that generated from diamond program. ?
Thanks

**Comment by Mohamed-ElhajAbdou** [comment]
**Solution**  after so many attempts here are the steps 

1- you just need to download the diamond .exe from this link  https://github.com/bbuchfink/diamond/releases/download/v0.9.31/diamond-windows.zip
2- do not forget to download the  Visual C++ Redistributable in this link 
https://www.microsoft.com/en-us/download/details.aspx?id=48145
3- after downloading the files unzip the dimoind.exe and take it and put in in your DeepGoPlus directory and write the command lines 
4- to test that everything is working right with you and diamond make your directory ( that you put the diomoind.exe there ) and then write diamond help 
5- here is the command that you can generate the diamond.res 
**diamond blastp -d data/train_data.dmnd -q data/test_data.fa --outfmt 6 qseqid sseqid bitscore > data/test_diamond.res**
note that 
train_data.dmnd can be found here 
http://deepgoplus.bio2vec.net/data/
