### ISSUE TITLE
AttributeError: 'Pandas' object has no attribute 'preds'

### ISSUE THREAD

**Issue by Mohamed-ElhajAbdou** [bio-ontology-research-group/deepgoplus#21]
I'm running now evaluate_deep_go_plus.py and I got this error   

<ipython-input-48-873532241439> in main(train_data_file, test_data_file, terms_file, diamond_scores_file, ont, alpha)
    103             annots_dict[go_id] *= alphas[go_rels.get_namespace(go_id)]
    104 
--> 105         for j, score in enumerate(row.preds):
    106 #             print ( deep_preds)
    107 #         for j, score in preds.iterrows():

AttributeError: 'Pandas' object has no attribute 'preds'

can you describe for me the source of error 
here is the inputs to the main function 
main('data/new/train_data.pkl','data/new/test_data.pkl','data/new/terms.pkl','data/test_diamond.res','mf',50)

**Comment by Mohamed-ElhajAbdou** [comment]
i got this error KeyError: 'A0A060X6Z0'  its a problem in dimoind file 

KeyError                                  Traceback (most recent call last)
<ipython-input-89-02718c176e08> in <module>()
     12             total_score = 0.0
     13             for p_id, score in sim_prots.items():
---> 14                 allgos |= annotations[prot_index[p_id]]
     15                 total_score += score
     16             allgos = list(sorted(allgos))

KeyError: 'A0A060X6Z0'

**Comment by coolmaksat** [comment]
When evaluating deepgoplus, you need to provide predictions.pkl file, which is
generated with deepgoplus.py. It is basically the same test_data.pkl dataframe
but with prediction scores. Provide predictions.pkl instead of test_data.pkl
