### ISSUE TITLE
Clarification on how the function `calculate_ic` works

### ISSUE THREAD

**Issue by samehkamaleldin** [bio-ontology-research-group/deepgoplus#23]
I wonder if you can explain the job of the function `calculate_ic`? https://github.com/bio-ontology-research-group/deepgoplus/blob/e031def1f0fb1921e8ae57d7b3ef1cbb2fc2e5fe/utils.py#L48

**Comment by coolmaksat** [comment]
Hi,
This function computes information content (IC) of the classes based on
the annotations. You can find detailed explanation for this specific IC measure here https://www.ncbi.nlm.nih.gov/pubmed/23813009.

**Comment by samehkamaleldin** [comment]
Thanks a lot. This helps.
