### ISSUE TITLE
Error: no such option: --data-root

### ISSUE THREAD

**Issue by aram10** [bio-ontology-research-group/deepgoplus#29]
When I try to run the command `deepgoplus --data-root <path_to_data_folder> --in-file <input_fasta_filename>` under Running I get this error.

**Comment by coolmaksat** [comment]
Could you please elaborate more on this. What is your python version? It seems to work for me.
How to reproduce it?

**Comment by aram10** [comment]
I've tried it on both Python 3.6 and 3.7. I created a folder named 'data' in the root directory, then I called the above command with train_data.fa as the in-file. I've attached a screenshot of my terminal. I see those commands in `main.py`, but calling it gives me an additional error about diamond not starting correctly.
![dgp](https://user-images.githubusercontent.com/59741191/101588703-fa3b0300-39b4-11eb-8c49-d2e34226982c.PNG)
![dgp1](https://user-images.githubusercontent.com/59741191/101588719-feffb700-39b4-11eb-9233-839a1b3319fe.PNG)

**Comment by coolmaksat** [comment]
You are using anaconda and I'm not sure if it works there. Could you please try to install it with virtualenv (or python3 -m venv)? And how did you install diamond? Did you get the binaries?

**Comment by aram10** [comment]
I am using Windows, so I downloaded and ran the executable (although it didn't look like anything happened). Also, which version of tensorflow needs to be used? I am using the latest version and upon compilation it looks like a number of the methods used are deprecated.

**Comment by coolmaksat** [comment]
Hi, I would suggest to use tensorflow 1.12.0, because it is the version we tested. And, install all the requirements from requirements.txt with ```pip install -r requirements.txt```

**Comment by coderwzz10** [comment]
data-root <path_to_data_folder> refers to the specific path where data is stored on your computer, use this path instead of data-root <path_to_data_folder>, no need to write it

**Comment by aram10** [comment]
I know to replace <path_to_data_folder>; I would still write out --data-root though, right?

Also, point of information, is the model.h5 file pre-trained? If so this would make my job easier; I am working on combining deepgoplus into an ensemble.

**Comment by coderwzz10** [comment]
you try not to write out data-root,and the model.h5 file should be pre-trained.
