### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by coderwzz10** [bio-ontology-research-group/deepgoplus#30]
Why does the link to download the data fail? Can't download data anymore

**Comment by coolmaksat** [comment]
Hi, we have recently moved our website to https://deepgo.cbrc.kaust.edu.sa and
all our data resides at https://deepgo.cbrc.kaust.edu.sa/data/. Please check if you
can access the links.

**Comment by coderwzz10** [comment]
Yes,I check it again,and I can't access the links.My main problem is that data-2019 in the deepgo data set I downloaded before seems to be missing a few files. I want to download it again this time, but can't access the links this time.Hope you can help me,thank you

**Comment by coolmaksat** [comment]
Okay, there seem to be a problem with our DNS records, I enabled the old links for now.
I think you can download the files now.

**Comment by coderwzz10** [comment]
Thank you very much
