### ISSUE TITLE
Some confusion about the web and local versions.

### ISSUE THREAD

**Issue by z4668640** [bio-ontology-research-group/deepgoplus#52]
I wanted to use DeepGoPlus to predict a fairly large number of sequences, but the web version can only request 10 sequences at a time, so I wanted to do it locally. 
However, I found that the code on Github is only available as version 1.01, while the latest version on the web is available as version 1.0.12.
I would like to ask how can I use the latest version of the program to predict a relatively large number of sequences?

**Comment by coolmaksat** [comment]
Hi,
You can download the data and model for the latest version with this link https://deepgo.cbrc.kaust.edu.sa/data/data-1.0.12.tar.gz

**Comment by z4668640** [comment]
> Hi, You can download the data and model for the latest version with this link https://deepgo.cbrc.kaust.edu.sa/data/data-1.0.12.tar.gz

Thank you very much for your help. Wish you a happy life.
