### ISSUE TITLE
Maybe 'pip install deepgoplus' needs a dependency update

### ISSUE THREAD

**Issue by z4668640** [bio-ontology-research-group/deepgoplus#55]
Maybe 'pip install deepgoplus' needs a dependency update, the' sklearn 'name has been deprecated, now you need' scikit-learn 'to install scikit-learn. Below I have included the error message when using 'pip install deepgoplus' directly.
![image](https://github.com/bio-ontology-research-group/deepgoplus/assets/71266093/646e9c6c-f9a6-41ca-a9fd-788763360e36)

**Comment by vahidodin** [comment]
I have the same problem !

**Comment by Jinghanpeng313** [comment]
I have the same problem !

**Comment by ferzcam** [comment]
As part of #40, we have updated the dependencies of DeepGOPlus.
