### ISSUE TITLE
Train model 

### ISSUE THREAD

**Issue by vahidodin** [bio-ontology-research-group/deepgoplus#56]
Hi 
I've installed deepgoplus. since Readme and Document are not clear, I couldn't understand what exactly to write in the "--in-file" input : 
 " deepgoplus --data-root C:\~\data-2016 --in-file ??? " Command. I tested all files inside the folder but got an error: 'Pandas' object has no attribute 'exp_annotations'
My goal is to train the 2016 dataset and test it after. If there are additional tips for the next steps, Please explain me.
Thank you for your help

**Comment by coolmaksat** [comment]
Hi, --in-file parameter is for a fasta file with protein sequences, and the data folder with trained models should be provided in --data-root argument (or default is 'data'). if you want to train the models, please use the deepgoplus.py script

**Comment by vahidodin** [comment]
Thank you 
In the training process, after going through several steps, I got the below error: 

AttributeError: 'Pandas' object has no attribute 'prop_annotations'

![Last_One - VMware Workstation 09_07_1402 02_24_42 ب ظ](https://github.com/bio-ontology-research-group/deepgoplus/assets/61935562/1b4c4fd2-8e78-4cd9-97e3-8a682508daca)


As it's necessary, I put the 2016 dataset on the root and changed its name to data.
I tried it on both Windows (Anaconda) and Ubuntu 18.04
Is there anything that I missed?

**Comment by coolmaksat** [comment]
Hi,
The problem is that in the data-2016 dataset we used column name 'annotations' which was updated to 'prop_annotations' in later version. Please change the row.prop_annotations to row.annotations in line 268 and everywhere else in the script

**Comment by vahidodin** [comment]
Hi
I've another question:
When I'm using "deepgoplus -dr /data -if test.fasta -of x.txt" for predicting protein function, I get this error : 
FileNotFoundError: [Errno 2] No such file or directory: './data/diamond.res'
There is not any file named diamond.res
should I create it myself ?
