### ISSUE TITLE
How can I evaluate deepgoplus with cafa3 data?

### ISSUE THREAD

**Issue by song2000012138** [bio-ontology-research-group/deepgoplus#57]
I trained model with your initial data-folder data and generated predictions.pkl and I use evaluate_deepgoplus.py to generated the Fmax、Smin、AUPR of mf、cc、bp and now I'm wondering how can I evaluate deepgoplus with cafa3 data to generate the results in Figure 2 in your article, is just replace the initial data-folder data with cafa3 data and genrate model and predictions.pkl and use evaluate_deepgoplus.py to generate the results of mf、bp、cc. what should i do, can you give me some guidance.

**Comment by coolmaksat** [comment]
Hi,
Yes, you are right, you just need to replace the data-folder with data-cafa3 folder. But you have to re-trainall the models again.

**Comment by song2000012138** [comment]
Thank you so much, but i'm curious about evaluate_cafa3.py、evaluate_deepgo.py what are they used for? At first i thought evaluate_cafa3.py was to evaluate deepgoplus with cafa3 dataset.

**Comment by coolmaksat** [comment]
The scripts are almost same, evaluate_cafa3 comes with some specific settings for cafa3 dataset. It should be used to evaluate cafa3 dataset.

**Comment by song2000012138** [comment]
OK, thank you so much
